AllCops:
  SuggestExtensions: false
  Exclude:
    - 'utils/texts.rb'
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Max: 40
Metrics/AbcSize:
  Max: 30
Lint/SuppressedException:
  Enabled: false