# utils/texts.rb
module Texts
  LOGIN_ERROR_MESSAGE = 'Epic sadface: Username and password do not match any user in this service'
  LOCKED_USER = "Epic sadface: Sorry, this user has been locked out."
  MAIN_PAGE = "Sauce Labs Backpack\ncarry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.\n$29.99\nAdd to cart\nSauce Labs Bike Light\nA red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.\n$9.99\nAdd to cart\nSauce Labs Bolt T-Shirt\nGet your testing superhero on with the Sauce Labs bolt T-shirt. From American Apparel, 100% ringspun combed cotton, heather gray with red bolt.\n$15.99\nAdd to cart\nSauce Labs Fleece Jacket\nIt's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office.\n$49.99\nAdd to cart\nSauce Labs Onesie\nRib snap infant onesie for the junior automation engineer in development. Reinforced 3-snap bottom closure, two-needle hemmed sleeved and bottom won't unravel.\n$7.99\nAdd to cart\nTest.allTheThings() T-Shirt (Red)\nThis classic Sauce Labs t-shirt is perfect to wear when cozying up to your keyboard to automate a few tests. Super-soft and comfy ringspun combed cotton.\n$15.99\nAdd to cart\nTwitter\nFacebook\nLinkedIn\n© 2025 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy"
  MODAL_TEXT = "THIS IS A MODAL WINDOW\nIt's commonly used to encourage a user to take an action (e.g., give their e-mail address to sign up for something or disable their ad blocker).\nClose"
  CHECKOUT = "Open Menu\nSwag Labs\nCheckout: Complete!\nThank you for your order!\nYour order has been dispatched, and will arrive just as fast as the pony can get there!\nBack Home\nTwitter\nFacebook\nLinkedIn\n© 2025 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy"
  BACKPACK = "Open Menu\nSwag Labs\n1\nCheckout: Overview\nQTYDescription\n1\nSauce Labs Backpack\ncarry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.\n$29.99\nPayment Information:\nSauceCard #31337\nShipping Information:\nFree Pony Express Delivery!\nPrice Total\nItem total: $29.99\nTax: $2.40\nTotal: $32.39\nCancelFinish\nTwitter\nFacebook\nLinkedIn\n© 2025 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy"
  BIKE = "Open Menu\nSwag Labs\n1\nCheckout: Overview\nQTYDescription\n1\nSauce Labs Bike Light\nA red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.\n$9.99\nPayment Information:\nSauceCard #31337\nShipping Information:\nFree Pony Express Delivery!\nPrice Total\nItem total: $9.99\nTax: $0.80\nTotal: $10.79\nCancelFinish\nTwitter\nFacebook\nLinkedIn\n© 2025 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy"
  BOLTTSHIRT = "Open Menu\nSwag Labs\n1\nCheckout: Overview\nQTYDescription\n1\nSauce Labs Bolt T-Shirt\nGet your testing superhero on with the Sauce Labs bolt T-shirt. From American Apparel, 100% ringspun combed cotton, heather gray with red bolt.\n$15.99\nPayment Information:\nSauceCard #31337\nShipping Information:\nFree Pony Express Delivery!\nPrice Total\nItem total: $15.99\nTax: $1.28\nTotal: $17.27\nCancelFinish\nTwitter\nFacebook\nLinkedIn\n© 2025 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy"
  JACKET = "Open Menu\nSwag Labs\n1\nCheckout: Overview\nQTYDescription\n1\nSauce Labs Fleece Jacket\nIt's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office.\n$49.99\nPayment Information:\nSauceCard #31337\nShipping Information:\nFree Pony Express Delivery!\nPrice Total\nItem total: $49.99\nTax: $4.00\nTotal: $53.99\nCancelFinish\nTwitter\nFacebook\nLinkedIn\n© 2025 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy"
  OBESIE = "Open Menu\nSwag Labs\n1\nCheckout: Overview\nQTYDescription\n1\nSauce Labs Onesie\nRib snap infant onesie for the junior automation engineer in development. Reinforced 3-snap bottom closure, two-needle hemmed sleeved and bottom won't unravel.\n$7.99\nPayment Information:\nSauceCard #31337\nShipping Information:\nFree Pony Express Delivery!\nPrice Total\nItem total: $7.99\nTax: $0.64\nTotal: $8.63\nCancelFinish\nTwitter\nFacebook\nLinkedIn\n© 2025 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy"
  REDTSHIRT = "Open Menu\nSwag Labs\n1\nCheckout: Overview\nQTYDescription\n1\nTest.allTheThings() T-Shirt (Red)\nThis classic Sauce Labs t-shirt is perfect to wear when cozying up to your keyboard to automate a few tests. Super-soft and comfy ringspun combed cotton.\n$15.99\nPayment Information:\nSauceCard #31337\nShipping Information:\nFree Pony Express Delivery!\nPrice Total\nItem total: $15.99\nTax: $1.28\nTotal: $17.27\nCancelFinish\nTwitter\nFacebook\nLinkedIn\n© 2025 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy"
end
