name: Run Tests with RSpec and Allure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_and_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxkbfile-dev \
            libsecret-1-dev \
            libnss3-dev \
            libgdk-pixbuf2.0-0 \
            libxss1 \
            libdbus-1-3 \
            libxtst6 \
            libappindicator3-1 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libdrm2 \
            libgtk-3-0

      - name: Install webdrivers gem and update chromedriver
        run: |
          gem install webdrivers
          bundle exec ruby -r 'webdrivers/chromedriver' -e "Webdrivers::Chromedriver.update"

      - name: Run RSpec tests and generate Allure results
        run: |
          mkdir -p report/allure-results
          bundle exec rspec --format AllureRspec::Formatter

      - name: Install Allure CLI
        uses: simple-elf/allure-report-action@master
        with:
          allure_version: 2.24.0

      - name: Generate Allure report
        run: |
          allure generate report/allure-results --clean -o report/allure-report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: report/allure-report

      - name: Display Allure report summary (optional)
        run: |
          allure report open report/allure-report
