name: Run RSpec with Capybara and Selenium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxkbfile-dev \
            libsecret-1-dev \
            libnss3-dev \
            libgconf-2-4 \
            libappindicator3-1 \
            libasound2 \
            libxtst6 \
            libgtk-3-0 \
            libxss1 \
            libdbus-1-3

      - name: Set up ChromeDriver
        run: |
          sudo apt-get install -y google-chrome-stable
          curl -sSL https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip -o chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Run tests
        run: |
          export CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
          webdrivers:chromedriver:update
          bundle exec rspec --tag ~slow --allure-results
          
      - name: Upload Allure Results
        if: always()
        uses: svenstaro/allure-action@v2
        with:
          allure_version: '2.16.1'
          results_dir: allure-results
          clean_results_dir: true
