name: CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  
  workflow_dispatch:

jobs:
  rspec:
    runs-on: ubuntu-latest

    container:
      image: ruby:3.4

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2 

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path vendor/bundle

    - name: Run RSpec tests
      run: |
        bundle exec rspec ./spec/features/*
