name: Run RSpec with Capybara and Selenium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxkbfile-dev \
            libsecret-1-dev \
            libnss3-dev \
            libgdk-pixbuf2.0-0 \
            libxss1 \
            libdbus-1-3 \
            libxtst6 \
            libappindicator3-1 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libdrm2 \
            libgtk-3-0

      - name: Install dependencies and update chromedriver
        run: |
          gem install webdrivers
          bundle install
          bundle exec ruby -r 'webdrivers/chromedriver' -e "Webdrivers::Chromedriver.update"

      - name: Run tests
        run: |
          export CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
          webdrivers:chromedriver:update
          bundle exec rspec --tag ~slow --allure-results
          
      - name: Upload Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

