name: Run Rspec

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Run Rspec
    types:
      - completed
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Test
        run: bundle exec rspec ./spec/features/*
