name: Ruby Tests with RSpec and Allure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install 

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
    - name: Install Allure and Google Chrome via Homebrew
      run: |
        brew install --cask google-chrome
        
        brew install allure

    - name: Run RSpec tests with Allure formatter
      run: |
        bundle exec rspec ./spec/features/* --format AllureRspecFormatter --out allure-results
      continue-on-error: true

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report
      continue-on-error: true

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
