name: Ruby Tests with Allure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'  # Specify the Ruby version you're using

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install  # Install Ruby dependencies from Gemfile

    - name: Install Allure
      run: |
        curl -sL https://github.com/allure-framework/allure2/releases/download/2.16.1/allure-2.16.1.zip -o allure.zip
        unzip allure.zip -d allure
        sudo mv allure /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    - name: Run tests with RSpec and Allure
      run: |
        bundle exec rspec ./spec/features/* 


    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
